### ISSUE TITLE
我汇总了一下数据

### ISSUE THREAD

**Issue by hellodword** [Treblex/wechat-feeds-page#1]
Hi~感谢你制作的页面

我现在将包括头像、更新时间在内的数据更新到了 [details.json](https://github.com/hellodword/wechat-feeds/blob/feeds/details.json)

同时之前有一个预留的 [pages 分支](https://github.com/hellodword/wechat-feeds/tree/pages) ，我稍微改了下你的源码加上了头像然后 force push 了上去，解析到了 [wechat.privacyhide.com](https://wechat.privacyhide.com/)，感谢信息写在了 readme 和页面的顶部~暂时有一些问题所以还没有写到主分支

如果你可以 pr 到这个分支就最好了~因为我是想之后也同步到 gitee，做一个镜像的 pages

**Comment by lazyfury** [comment]
OK
